services:
    mynode:
      build: .
      ports:
        - "8080:8080"
      environment:
        DB_URI: mongodb://mongo:27017/local_test
      depends_on:
        - mongo

    
    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
