name: Run tests on PR

on:
  pull_request:
    types: [opened]
    branches: [main]


jobs:
  testing:
    runs-on: ubuntu-latest
    environment: test
    env:
      ${{ secrets }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: List Directories
        run: ls -R

# caching the dependency
      - name: 'Cache Dependencies'
        uses: 'actions/cache@v3'
        id: cache-node-modules
        with:
          path: './node_modules'
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        # only run npm i if cache not found
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: List Directories After
        run: ls -R

      - name: Running tests
        run: npm run test

#if this is not working then I will try something else
