name: Run tests on PR

on:
  pull_request:
    types: [opened]
    branches: [main]


jobs:
  testing:
    runs-on: ubuntu-latest
    environment: test
    env:
      ${{ secrets }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Running tests
        run: npm run tests
